import streamlit as st
import os
import tempfile
from pathlib import Path
from datetime import datetime
import sys

# Page configuration
st.set_page_config(
    page_title="AI Transcriber",
    page_icon="🎙️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for premium design
st.markdown("""
<style>
    .main-header {
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        padding: 2rem;
        border-radius: 1rem;
        margin-bottom: 2rem;
        color: white;
        text-align: center;
    }
    .success-box {
        background: #d4edda;
        border: 1px solid #c3e6cb;
        color: #155724;
        padding: 1rem;
        border-radius: 0.5rem;
        margin: 1rem 0;
    }
    .transcript-container {
        background: #ffffff;
        padding: 2rem;
        border-radius: 1rem;
        border: 1px solid #dee2e6;
        margin: 1rem 0;
        max-height: 500px;
        overflow-y: auto;
    }
    .timestamp {
        color: #667eea;
        font-weight: bold;
        font-family: monospace;
    }
    .info-badge {
        background: #e7f3ff;
        color: #0056b3;
        padding: 0.25rem 0.75rem;
        border-radius: 1rem;
        font-size: 0.875rem;
        display: inline-block;
        margin: 0.25rem;
    }
    .chunk-info {
        background: #fff3cd;
        border: 1px solid #ffc107;
        padding: 0.5rem 1rem;
        border-radius: 0.5rem;
        font-size: 0.85rem;
        margin: 0.5rem 0;
    }
</style>
""", unsafe_allow_html=True)

# -------------------------------------------------------------------------
# Session state initialisation
# -------------------------------------------------------------------------
if 'transcription_result' not in st.session_state:
    st.session_state.transcription_result = None
if 'current_file' not in st.session_state:
    st.session_state.current_file = None
if 'processing' not in st.session_state:
    st.session_state.processing = False

# -------------------------------------------------------------------------
# Header
# -------------------------------------------------------------------------
st.markdown("""
<div class="main-header">
    <h1>🎙️ AI Video Transcriber</h1>
    <p>Transform your videos into text with local AI - No cloud, No data leaks</p>
</div>
""", unsafe_allow_html=True)

# -------------------------------------------------------------------------
# Import transcription services
# -------------------------------------------------------------------------
sys.path.append(str(Path(__file__).parent))

try:
    from services.transcriber import transcribe_file, TranscriptionResult
except ImportError as _import_err:
    st.error(f"❌ Failed to import transcription services: {_import_err}")
    st.stop()

# -------------------------------------------------------------------------
# Export format helpers  (unchanged from original)
# -------------------------------------------------------------------------

def create_srt_content(segments) -> str:
    """Create SRT subtitle format content."""
    lines = []
    for i, seg in enumerate(segments):
        def _fmt(t: float) -> str:
            h = int(t // 3600)
            m = int((t % 3600) // 60)
            s = int(t % 60)
            ms = int((t % 1) * 1000)
            return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"
        lines.extend([
            str(i + 1),
            f"{_fmt(seg.start)} --> {_fmt(seg.end)}",
            seg.text,
            "",
        ])
    return "\n".join(lines)


def create_vtt_content(segments) -> str:
    """Create WebVTT subtitle format content."""
    lines = ["WEBVTT", ""]
    for i, seg in enumerate(segments):
        def _fmt(t: float) -> str:
            h = int(t // 3600)
            m = int((t % 3600) // 60)
            s = int(t % 60)
            ms = int((t % 1) * 1000)
            return f"{h:02d}:{m:02d}:{s:02d}.{ms:03d}"
        lines.extend([
            str(i + 1),
            f"{_fmt(seg.start)} --> {_fmt(seg.end)}",
            seg.text,
            "",
        ])
    return "\n".join(lines)


def create_docx_content(text: str) -> str:
    """Create DOCX content (simple text-based approach)."""
    return (
        f"TRANSCRIPT\n{'=' * 50}\n\n{text}\n\n"
        f"Generated by AI Transcriber\nDeveloped by Zaid Hassan\n\n"
        f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    )


def create_pdf_content(text: str) -> str:
    """Create PDF content (basic text-based approach)."""
    return (
        f"TRANSCRIPT\n{'=' * 50}\n\n{text}\n\n"
        f"Generated by AI Transcriber\nDeveloped by Zaid Hassan\n\n"
        f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    )

# -------------------------------------------------------------------------
# Sidebar
# -------------------------------------------------------------------------
with st.sidebar:
    st.markdown("### 📋 Instructions")
    st.markdown("""
    1. **Upload** a video file (MP4, MOV, AVI, MKV, WEBM)
    2. **Click** "Start Transcription"
    3. **Wait** for AI processing
    4. **Download** your transcript in multiple formats
    """)

    st.markdown("---")
    st.markdown("### 🔒 Privacy First")
    st.markdown("""
    - ✅ Local processing only
    - ✅ No data sent to cloud
    - ✅ Works offline after setup
    - ✅ Your data stays private
    """)

    st.markdown("---")
    st.markdown("### ⚙️ Settings")

    model_size = st.selectbox(
        "AI Model Size",
        ["tiny", "base", "small", "medium"],
        index=1,
        help=(
            "**tiny** – fastest, lowest RAM (~1 GB peak). Recommended for videos > 30 min.\n"
            "**base** – good balance of speed and accuracy (~1.5 GB peak).\n"
            "**small** – more accurate, slower (~2 GB peak).\n"
            "**medium** – best accuracy, may exceed free cloud RAM limits."
        ),
    )

    chunk_minutes = st.slider(
        "Chunk Duration (minutes)",
        min_value=5,
        max_value=15,
        value=10,
        step=5,
        help=(
            "Long videos are split into chunks of this duration. "
            "Each chunk is processed and freed from memory before the next one. "
            "Smaller chunks = lower peak RAM. 10 min is a safe default."
        ),
    )

    st.markdown("---")
    st.markdown("### 💡 Long Video Tips")
    st.markdown("""
    - Use **tiny** or **base** model for 30–60 min videos
    - **10-min chunks** keep peak RAM below 1.5 GB
    - Processing time ≈ 1–2× video length on CPU
    - Do **not** reload the page while processing
    """)

    st.markdown("---")
    st.markdown("### 👨‍💻 Developer")
    st.markdown("Developed by [Zaid Hassan](https://zaidhassan.me)")

# -------------------------------------------------------------------------
# Main content — Upload
# -------------------------------------------------------------------------
st.markdown("## 📁 Upload Video File")

uploaded_file = st.file_uploader(
    "Choose a video file",
    type=['mp4', 'mov', 'avi', 'mkv', 'webm'],
    help="Supported formats: MP4, MOV, AVI, MKV, WEBM",
)

if uploaded_file:
    st.markdown(f"""
    <div class="info-badge">
        📄 File: {uploaded_file.name}
    </div>
    <div class="info-badge">
        📊 Size: {uploaded_file.size / (1024 * 1024):.2f} MB
    </div>
    """, unsafe_allow_html=True)

    # Estimate chunks for display
    # We don't know duration yet, but size/bitrate gives a rough estimate
    _est_min = uploaded_file.size / (1024 * 1024 * 0.5)  # ~0.5 MB/s audio
    _est_chunks = max(1, int(_est_min / chunk_minutes) + 1)
    if uploaded_file.size > 50 * 1024 * 1024:  # show hint for files > 50 MB
        st.markdown(
            f'<div class="chunk-info">ℹ️ This file will be split into approximately '
            f'<strong>{_est_chunks} chunk(s)</strong> of {chunk_minutes} minutes each '
            f'— only one chunk lives in RAM at a time.</div>',
            unsafe_allow_html=True,
        )

    col1, col2 = st.columns([1, 1])
    with col1:
        start_button = st.button(
            "🚀 Start Transcription",
            type="primary",
            disabled=st.session_state.processing,
        )
    with col2:
        clear_button = st.button("🗑️ Clear", disabled=st.session_state.processing)

    if clear_button:
        st.session_state.current_file = None
        st.session_state.transcription_result = None
        st.rerun()

    if start_button and not st.session_state.processing:
        st.session_state.processing = True
        st.session_state.current_file = uploaded_file.name
        st.session_state.transcription_result = None

        # ------------------------------------------------------------------ #
        # IMPORTANT: Stream the uploaded file to disk in 4 MB chunks.        #
        # This avoids loading the entire video into Python RAM with           #
        # uploaded_file.getvalue() or .getbuffer().                          #
        # ------------------------------------------------------------------ #
        suffix = Path(uploaded_file.name).suffix or ".mp4"
        tmp_video_fd, tmp_video_path_str = tempfile.mkstemp(suffix=suffix)
        tmp_video_path = Path(tmp_video_path_str)

        progress_bar = st.progress(0)
        status_text = st.empty()

        try:
            # --- Stream upload to disk ---
            status_text.text("💾 Saving uploaded video to disk…")
            progress_bar.progress(2)

            CHUNK_SIZE = 4 * 1024 * 1024  # 4 MB write buffer
            total_written = 0
            with os.fdopen(tmp_video_fd, "wb") as f:
                uploaded_file.seek(0)
                while True:
                    data = uploaded_file.read(CHUNK_SIZE)
                    if not data:
                        break
                    f.write(data)
                    total_written += len(data)

            progress_bar.progress(5)
            status_text.text(
                f"✅ Video saved ({total_written / (1024 * 1024):.1f} MB). "
                "Preparing transcription…"
            )

            # ---------------------------------------------------------------- #
            # Progress callback — maps internal progress (0–100) to bar       #
            # ---------------------------------------------------------------- #
            def progress_callback(percent: int, message: str) -> None:
                # Reserve first 5% for upload, last 0% for display finish
                scaled = 5 + int(percent * 0.94)
                progress_bar.progress(min(scaled, 99))
                status_text.text(f"🔄 {message}")

            # ---------------------------------------------------------------- #
            # Run transcription                                                 #
            # ---------------------------------------------------------------- #
            result = transcribe_file(
                tmp_video_path,
                model_name=model_size,
                progress_callback=progress_callback,
                chunk_minutes=chunk_minutes,
            )

            progress_bar.progress(100)
            status_text.text("✅ Transcription complete!")

            # Store only the lightweight result object (text + segment list)
            # Do NOT store the video/audio bytes in session_state
            st.session_state.transcription_result = result
            st.session_state.processing = False

        except Exception as exc:
            st.session_state.processing = False
            status_text.text("❌ Transcription failed.")
            st.error(f"**Error:** {exc}")
            import traceback
            with st.expander("🔍 Technical details (for debugging)"):
                st.code(traceback.format_exc())

        finally:
            # Always clean up the temporary video file
            try:
                if tmp_video_path.exists():
                    tmp_video_path.unlink()
            except Exception:
                pass

        st.rerun()

elif st.session_state.processing:
    st.info("⏳ Processing in progress… Please wait and do not reload the page.")

# -------------------------------------------------------------------------
# Display transcription results
# -------------------------------------------------------------------------
if st.session_state.transcription_result:
    result = st.session_state.transcription_result

    st.markdown("---")
    st.markdown("## ✅ Transcription Complete!")

    st.markdown(f"""
    <div class="success-box">
        <strong>🎉 Success!</strong> Your video has been transcribed with
        <strong>{len(result.segments)}</strong> segment(s).
        {f'Detected language: <strong>{result.language}</strong>.' if result.language else ''}
    </div>
    """, unsafe_allow_html=True)

    # ---- Transcript viewer ----
    st.markdown("### 📝 Transcript")
    st.text_area(
        "Full Transcript",
        result.text,
        height=300,
        key="transcript_text",
    )

    # ---- Timestamped segments ----
    with st.expander("🕐 View Timestamped Segments", expanded=False):
        for segment in result.segments:
            h = int(segment.start // 3600)
            m = int((segment.start % 3600) // 60)
            s = int(segment.start % 60)
            timestamp = f"[{h:02d}:{m:02d}:{s:02d}]"
            st.markdown(
                f'<div class="transcript-container">'
                f'<span class="timestamp">{timestamp}</span> {segment.text}'
                f'</div>',
                unsafe_allow_html=True,
            )

    # ---- Download buttons ----
    st.markdown("---")
    st.markdown("### 💾 Download Transcript")

    ts = datetime.now().strftime('%Y%m%d_%H%M%S')

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        if st.button("📋 Copy Text"):
            st.code(result.text, language=None)

    with col2:
        st.download_button(
            label="📄 Download .TXT",
            data=result.text,
            file_name=f"transcript_{ts}.txt",
            mime="text/plain",
        )

    with col3:
        st.download_button(
            label="🎬 Download .SRT",
            data=create_srt_content(result.segments),
            file_name=f"transcript_{ts}.srt",
            mime="text/plain",
        )

    with col4:
        st.download_button(
            label="🌐 Download .VTT",
            data=create_vtt_content(result.segments),
            file_name=f"transcript_{ts}.vtt",
            mime="text/vtt",
        )

    st.markdown("### 📄 Additional Formats")
    col5, col6 = st.columns(2)

    with col5:
        st.download_button(
            label="📑 Download .DOCX",
            data=create_docx_content(result.text),
            file_name=f"transcript_{ts}.docx",
            mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        )

    with col6:
        st.download_button(
            label="📕 Download .PDF",
            data=create_pdf_content(result.text),
            file_name=f"transcript_{ts}.pdf",
            mime="application/pdf",
        )

    # ---- Reset ----
    st.markdown("---")
    if st.button("🔄 Process Another Video"):
        st.session_state.transcription_result = None
        st.session_state.current_file = None
        st.rerun()

# -------------------------------------------------------------------------
# Footer
# -------------------------------------------------------------------------
st.markdown("---")
st.markdown("""
<div style="text-align: center; color: #666; padding: 1rem;">
    <p>🎙️ AI Transcriber | Local AI-Powered Speech to Text</p>
    <p>Developed by <a href="https://zaidhassan.me" target="_blank">Zaid Hassan</a></p>
</div>
""", unsafe_allow_html=True)
